name: ci

on:
  pull_request:
    branches: [main]


jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Ste up Go
        uses: actions/setup-go@v5
        with:
          go-verssion: "1.25.1"

      - name: Force Failure
        run: (go version)
